name: mmone
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6
  - plyfile
  - python=3.7.16
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - opencv
  - tensorboard
  - jaxtyping
  - matplotlib
  - typing
  - pathlib
  - ftfy==6.1.1
  - open-clip-torch==2.24.0
  - mediapy==1.1.2
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/language-rasterization
    - submodules/simple-knn
